FileVersion = 1
Dependencies = {corlib = "*", allegro = "*"}

[Project]
Name = "allegro_primitives"
TargetType = "BeefLib"
StartupObject = "allegro_primitives.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\allegro_primitives-debug-static.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\allegro_primitives-static.lib"]
