FileVersion = 1
Dependencies = {corlib = "*", allegro = "*"}

[Project]
Name = "allegro_image"
TargetType = "BeefLib"
StartupObject = "allegro_image.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\allegro_image-static.lib"]
