FileVersion = 1
Dependencies = {corlib = "*", allegro = "*"}

[Project]
Name = "allegro_font"
TargetType = "BeefLib"
StartupObject = "allegro_font.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\allegro_font-static.lib"]
