FileVersion = 1
Dependencies = {corlib = "*", allegro = "*"}

[Project]
Name = "allegro_audio"
TargetType = "BeefLib"
StartupObject = "allegro_audio.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\allegro_audio-debug-static.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\allegro_audio-static.lib"]
