FileVersion = 1
Dependencies = {corlib = "*", allegro = "*"}

[Project]
Name = "allegro_native_dialog"
TargetType = "BeefLib"
StartupObject = "allegro_native_dialog.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\allegro_dialog-static.lib"]
