FileVersion = 1
Dependencies = {corlib = "*", allegro = "*", allegro_audio = "*"}

[Project]
Name = "allegro_acodec"
TargetType = "BeefLib"
StartupObject = "allegro_acodec.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\allegro_acodec-debug-static.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\allegro_acodec-static.lib"]
